/*
 * Report Generation Module
 *
 * Generates comprehensive HTML and Markdown reports summarizing
 * the analysis results and quality metrics.
 *
 * Input:
 *   - scored: List of scored Nm site files
 *   - regional: List of regional distribution files
 *   - motif: List of motif analysis files
 *   - plots: List of generated plots
 *   - output_dir: Output directory
 *
 * Output:
 *   - report: Generated report files
 */

process GENERATE_REPORT {
    tag "REPORT"
    label 'report'

    publishDir "${params.output_dir}/reports",
        mode: params.publish_mode,
        pattern: "*.{html,md,json}",
        saveAs: { filename -> "${filename}" }

    input:
    path scored_files
    path regional_files
    path motif_files
    path plot_files
    val output_dir

    output:
    path "nju_seq_report.html", emit: html_report
    path "nju_seq_report.md", emit: md_report
    path "summary_statistics.json", emit: json_summary
    path "*.{html,md,json}", emit: report

    script:
    """
    # Generate summary statistics using external Python script
    python3 "${baseDir}/scripts/generate_summary.py" "${scored_files.join(' ')}" "${regional_files.join(' ')}" "${motif_files.join(' ')}" "${plot_files.join(' ')}"
    

    # Generate HTML report
    cat > nju_seq_report.md << 'EOF'
# NJU-seq Analysis Report

## Overview

This report summarizes the comprehensive Nm-site analysis results generated by the NJU-seq pipeline.

## Pipeline Summary

- **Pipeline**: NJU-seq (Nm-site Judged Universally sequencing)
- **Version**: 1.0.0
- **Date**: $(date '+%Y-%m-%d %H:%M:%S')

## Analysis Results

### Nm-site Identification

Detailed Nm-site identification results are available in the following files:

- Leaf tissue: `mrna.filter.Ath_leaf_RF.tsv`
- Root tissue: `mrna.filter.Ath_root_RF.tsv`
- Stem tissue: `mrna.filter.Ath_stem_RF.tsv`
- Flower tissue: `mrna.filter.Ath_flower_RF.tsv`

### Regional Distribution

Genomic regional distribution analysis results:

- UTR5, UTR3, CDS, and intron distribution for each tissue
- Pie charts and bar plots in `figures/` directory

### Motif Analysis

Sequence motif analysis around Nm sites:

- Motif frequency analysis
- Sequence logo generation
- Cross-tissue comparison

## Quality Metrics

### Alignment Statistics

Alignment quality metrics are available in:

- `*_bowtie2.log` files for each sample
- Summary statistics in `reports/` directory

### Filtering Statistics

Filtering efficiency metrics:

- Bacterial RNA removal
- rRNA removal
- Duplication rates

## Output Files

All analysis results are organized in the following structure:

```
${params.output_dir}/
├── NJU62{20..35}/
│   ├── bac_rna.raw.sam
│   ├── rrna.filter.sam
│   ├── mrna.filter.sam
│   └── ...
├── mrna.filter.*_RF.tsv
├── regional_analysis/
├── motif_analysis/
├── figures/
└── reports/
```

## Conclusions

The NJU-seq pipeline successfully identified Nm modification sites across
different Arabidopsis thaliana tissues. Detailed analysis reveals:

1. Tissue-specific Nm site preferences
2. Distinct sequence motif patterns
3. Regional distribution characteristics

---
Generated by NJU-seq Pipeline v1.0.0
EOF

    # Convert markdown to HTML
    if command -v pandoc &> /dev/null; then
        pandoc nju_seq_report.md -o nju_seq_report.html \
            --standalone \
            --metadata title="NJU-seq Analysis Report" \
            --css https://cdn.jsdelivr.net/npm/github-markdown-css@5.1.0/github-markdown.min.css
    else
        cat > nju_seq_report.html << 'HTMLEOF'
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>NJU-seq Analysis Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; max-width: 1200px; }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; }
        h2 { color: #34495e; margin-top: 30px; }
        pre { background: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto; }
        code { background: #f8f9fa; padding: 2px 6px; border-radius: 3px; }
    </style>
</head>
<body class="markdown-body">
    <h1>NJU-seq Analysis Report</h1>
    <p><strong>Pipeline:</strong> NJU-seq (Nm-site Judged Universally sequencing)</p>
    <p><strong>Generated:</strong> $(date '+%Y-%m-%d %H:%M:%S')</p>
    <p>For detailed analysis results, please refer to the Markdown version of this report.</p>
</body>
</html>
HTMLEOF
    fi

    echo "Report generation completed successfully"
    """
}
